name: zl2-hw3-topic1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.11.0
      - torchvision==0.26.0
      - opencv-python==4.13.0.92
      - pillow==12.1.1
      - numpy==2.2.6
      - trimesh==4.12.2
      - imageio==2.37.3
      - imageio-ffmpeg==0.6.0
      - scikit-image==0.25.2
      - reportlab==5.0.0
      - rembg==2.0.69
      - onnxruntime==1.23.2
